Updated the GitHub workflows and/or the README file to the latest versions.

diff --git a/.github/workflows/R-CMD-check.yaml b/.github/workflows/R-CMD-check.yaml
--- a/.github/workflows/R-CMD-check.yaml
+++ b/.github/workflows/R-CMD-check.yaml
@@ -3,8 +3,34 @@
 # For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
 # https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
 
-# TODO:
-# * Sort out the builders for the PDF manuals and vignettes (since a tex installation may be needed for those), perhaps depending on the OS.
+# Each entry in the config matrix must have the following keys:
+#
+# os: windows-latest, macOS-latest, ubuntu-20.04, etc. (as of this writing)
+#
+# r: devel or release
+#
+# rspm: Linux only, just leave it alone.
+#
+# timeout: in minutes
+#
+# flags: a comma (or some other aesthetically pleasing and
+#   non-forbidden symbol) separated list of flags. Currently
+#   supported:
+#
+#   binaries: build and upload as an artefact a binary version (particularly for MacOS and Windows).
+#
+#   full: run with ENABLE_statnet_TESTS.
+#
+#   vignettes: build vignettes and manuals; otherwise ignore.
+#
+#   ubsan: compile with -fsanitize=undefined and fail on any errors identified.
+#
+#   debug: compile package with -DDEBUG and -UNDEBUG
+#
+#   covr: run in covr mode may be used with 'full' but probably not with others.
+#
+#
+# Typical public, private, and release configurations are provided in the variables below.
 
 on: [push, pull_request]
 
@@ -14,19 +40,23 @@ name: R-CMD-check
 env:
   PUBLIC: ''
   PRIVATE: ''
+  PUBLIC_CONFIG: '{"config":[
+            {"os":"windows-latest", "r":"release", "timeout":360, "flags":"binaries"},
+            {"os":"macOS-latest", "r":"release", "timeout":360, "flags":"binaries, ubsan"},
+            {"os":"ubuntu-latest", "r":"release", "timeout":360, "flags":"full, ubsan, debug"},
+            {"os":"ubuntu-latest", "r":"devel", "timeout":360, "flags":"vignettes, remote"},
+            {"os":"ubuntu-latest", "r":"release", "timeout":360, "flags":"full, covr"}]}'
+  RELEASE_CONFIG: '{"config":[
+            {"os":"windows-latest", "r":"release", "timeout":360, "flags":"binaries, vignettes, remote, strict"},
+            {"os":"macOS-latest", "r":"release", "timeout":360, "flags":"binaries, ubsan, vignettes, remote, strict"},
+            {"os":"ubuntu-latest", "r":"release", "timeout":360, "flags":"full, ubsan, debug, strict"},
+            {"os":"ubuntu-latest", "r":"devel", "timeout":360, "flags":"vignettes, remote, strict"},
+            {"os":"ubuntu-latest", "r":"release", "timeout":360, "flags":"full, covr, strict"}]}'
+  PRIVATE_CONFIG: '{"config":[
+            {"os":"ubuntu-latest", "r":"release", "timeout":10, "flags":"none"}
+            ]}'
 
 jobs:
-## Remove-Old-Artifacts:
-##   runs-on: ubuntu-latest
-##   timeout-minutes: 10
-##
-##   steps:
-##   - name: Remove old artifacts
-##     uses: c-hive/gha-remove-artifacts@v1.2.0
-##     with:
-##       age: '1 month'
-##       skip-recent: 8
-
   Set-Matrix-Private:
     runs-on: ubuntu-latest
     outputs:
@@ -64,13 +94,16 @@ jobs:
         run: |
           if [[ "${{ env.IAM }}" == 'public' ]] # Public: full set.
           then
-            echo "::set-output name=matrix::{\"config\":[{\"os\":\"windows-latest\", \"r\":\"release\", \"timeout\":360, \"full\":\"no\"}, {\"os\":\"macOS-latest\", \"r\":\"release\", \"timeout\":360, \"full\":\"no\"}, {\"os\":\"ubuntu-20.04\", \"r\":\"release\", \"rspm\":\"https://packagemanager.rstudio.com/cran/__linux__/focal/latest\", \"timeout\":360, \"full\":\"yes\"}, {\"os\":\"ubuntu-20.04\", \"r\":\"devel\", \"rspm\":\"https://packagemanager.rstudio.com/cran/__linux__/focal/latest\", \"timeout\":360, \"full\":\"no\"}]}"
+            config='${{ env.PUBLIC_CONFIG }}'
           elif [[ "${{ env.FOUND_PUBLIC }}" != '0' ]] # Private with no public analogue: reduced set.
           then
-            echo "::set-output name=matrix::{\"config\":[{\"os\":\"ubuntu-20.04\", \"r\":\"release\", \"rspm\":\"https://packagemanager.rstudio.com/cran/__linux__/focal/latest\", \"timeout\":10, \"full\":\"no\"}]}"
-          else
-            echo "::set-output name=matrix::" # Private with public analogue: no checking.
+            config='${{ env.PRIVATE_CONFIG }}'
+          else # Private with public analogue: no checking.
+            config=''
           fi
+          config="${config//$'\r'/' '}"
+          config="${config//$'\n'/' '}"
+          echo "matrix=$config" >> $GITHUB_OUTPUT
 
   R-CMD-check:
     needs: Set-Matrix-Private
@@ -79,15 +112,15 @@ jobs:
 
     runs-on: ${{ matrix.config.os }}
 
-    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
+    name: ${{ matrix.config.os }} (r ${{ matrix.config.r }}, flags ${{ matrix.config.flags }})
 
     strategy:
       fail-fast: false
       matrix: ${{fromJson(needs.Set-Matrix-Private.outputs.matrix)}}
 
     env:
+      HOMEBREW_NO_INSTALL_CLEANUP: 1
       R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
-      RSPM: ${{ matrix.config.rspm }}
 
     steps:
       - name: If available, use the Janitor's key rather than the repository-specific key.
@@ -101,75 +134,157 @@ jobs:
           fi
         shell: bash
 
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v4
 
-      - uses: r-lib/actions/setup-r@v1
+      - uses: r-lib/actions/setup-r@v2
         with:
+          use-public-rspm: true
           r-version: ${{ matrix.config.r }}
 
-      - uses: r-lib/actions/setup-pandoc@v1
-
-      - name: Query dependencies
+      - name: Install tidy (on Linux if running vignettes)
+        if: runner.os == 'Linux' && contains(matrix.config.flags, 'vignettes')
         run: |
-          install.packages('remotes')
-          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
-          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
-        shell: Rscript {0}
+          /usr/bin/sudo DEBIAN_FRONTEND=noninteractive apt-get install -y tidy
+        shell: bash
 
-      - name: Cache R packages
-        if: runner.os != 'Windows'
-        uses: actions/cache@v2
+      - uses: r-lib/actions/setup-pandoc@v2
+
+      - name: Install tinytex (system)
+        if: contains(matrix.config.flags, 'vignettes')
+        uses: r-lib/actions/setup-tinytex@v2
+
+      - uses: r-lib/actions/setup-r-dependencies@v2
         with:
-          path: ${{ env.R_LIBS_USER }}
-          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
-          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
+          extra-packages: |
+            any::rcmdcheck
+            any::covr
+            any::V8
+            any::xml2
+          needs: |
+            check
+            coverage
 
-      - name: Install system dependencies
-        if: runner.os == 'Linux'
+      - name: Install tinytex (R)
+        if: contains(matrix.config.flags, 'vignettes')
         run: |
-          while read -r cmd
-          do
-            eval sudo $cmd
-          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "20.04"))')
-
-      - name: Install dependencies
-        run: |
-          remotes::install_deps(dependencies = TRUE)
-          remotes::install_cran("pkgbuild")
-          remotes::install_cran("rcmdcheck")
+          if(!requireNamespace("tinytex", quietly = TRUE)) pak::pkg_install("tinytex")
+          tinytex:::install_yihui_pkgs()
+          tinytex::tlmgr_install("makeindex")
         shell: Rscript {0}
 
       - name: Build
-        if: runner.os != 'Linux'
+        if: contains(matrix.config.flags, 'binaries')
         run: |
           dir.create("binaries", FALSE)
           pkgbuild::build(binary=TRUE, vignettes=FALSE, dest_path = "binaries")
         shell: Rscript {0}
 
       - name: Upload build results
-        if: runner.os != 'Linux' && !failure()
-        uses: actions/upload-artifact@main
+        if: contains(matrix.config.flags, 'binaries') && !failure()
+        uses: actions/upload-artifact@v4
         with:
           name: ${{ runner.os }}-r${{ matrix.config.r }}-binaries
           path: binaries
 
       - name: Clean up build results
-        if: runner.os != 'Linux'
+        if: contains(matrix.config.flags, 'binaries')
         run: rm -rf binaries
         shell: bash
 
       - name: Check
+        if: contains(matrix.config.flags, 'covr') == false
+        timeout-minutes: ${{ matrix.config.timeout }}
+        env:
+          _R_CHECK_CRAN_INCOMING_REMOTE_: ${{ contains(matrix.config.flags, 'remote') }}
+          _R_CHECK_FORCE_SUGGESTS_: false
+          ENABLE_statnet_TESTS: ${{ contains(matrix.config.flags, 'full') }}
+          R_VIGNETTES: ${{ contains(matrix.config.flags, 'vignettes') }}
+          FAIL_ON_WARN: ${{ contains(matrix.config.flags, 'strict') }}
+          USE_UBSAN: ${{ contains(matrix.config.flags, 'ubsan') }}
+          SET_DEBUG: ${{ contains(matrix.config.flags, 'debug') }}
+        run: |
+          if(Sys.getenv("R_VIGNETTES") == "true"){
+            check_args <- c("--as-cran")
+            build_args <- c("--compact-vignettes=gs+qpdf")
+          }else{
+            check_args <- c("--no-manual", "--as-cran", "--ignore-vignettes")
+            build_args <- c("--no-manual", "--no-build-vignettes")
+          }
+
+          if(Sys.getenv("ENABLE_statnet_TESTS") == "true"){
+            check_args <- c(check_args, "--run-donttest")
+          }
+
+          error_on <- if(Sys.getenv("FAIL_ON_WARN") == "true") "warning" else "error"
+
+          extra_flags <- c()
+
+          if(Sys.getenv("USE_UBSAN") == "true"){
+            extra_flags <- c(extra_flags, "-fsanitize=undefined")
+            Sys.setenv(UBSAN_OPTIONS=paste(Sys.getenv("UBSAN_OPTIONS"), "print_stacktrace=1"))
+          }
+
+          if(Sys.getenv("SET_DEBUG") == "true") extra_flags <- c(extra_flags, "-UNDEBUG", "-DDEBUG")
+
+          # Before R 4.3.0, R itself was not compliant.
+          if(getRversion() >= "4.3") extra_flags <- c(extra_flags, "-Wstrict-prototypes")
+
+          Sys.setenv(PKG_LIBS=paste(c(Sys.getenv("PKG_LIBS"), extra_flags), collapse=" "),
+                     PKG_CXXFLAGS=paste(c(Sys.getenv("PKG_CXXFLAGS"), extra_flags), collapse=" "),
+                     PKG_CFLAGS=paste(c(Sys.getenv("PKG_CFLAGS"), extra_flags), collapse=" "))
+
+          rcmdcheck::rcmdcheck(args = check_args, build_args = build_args, error_on = error_on, check_dir = "check")
+        shell: Rscript {0}
+
+      - name: Check UBSAN output
+        if: contains(matrix.config.flags, 'ubsan')
+        # NB: xargs -r only works in GNU, so not on MacOS.
+        run: |
+          find check/ -name '*.Rout' -print0 > check/Rout.list
+          if [ -s check/Rout.list ]
+          then
+            cat check/Rout.list | xargs -0 grep -E '\.[hc]:[0-9]+:[0-9]+: +runtime error:' > check/ubsan.err || true
+            if [ -s check/ubsan.err ]
+            then
+              echo "UBSAN errors:" >&2
+              cat check/ubsan.err >&2
+              exit 1
+            fi
+          fi
+        shell: bash
+
+      - name: Upload check results
+        if: contains(matrix.config.flags, 'covr') == false && failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
+          path: |
+            check
+            !check/*/00_pkg_src
+
+      - name: Test coverage
+        if: ${{ contains(matrix.config.flags, 'covr') && hashFiles('codecov.yml') != '' }}
         timeout-minutes: ${{ matrix.config.timeout }}
         env:
           _R_CHECK_CRAN_INCOMING_REMOTE_: false
           _R_CHECK_FORCE_SUGGESTS_: ${{ runner.os != 'macOS' }} # Rmpi is not available on macOS.
-          ENABLE_statnet_TESTS: ${{ matrix.config.full }}
-        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran", "--no-build-vignettes"), build_args = c("--no-manual", "--no-build-vignettes"), error_on = "error", check_dir = "check")
+          ENABLE_statnet_TESTS: ${{ contains(matrix.config.flags, 'full') }}
+        run: |
+          cov <- covr::package_coverage(
+            type=c("tests", "examples"),
+            quiet = FALSE,
+            clean = FALSE,
+            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
+          )
+          covr::to_cobertura(cov)
         shell: Rscript {0}
 
-      - name: Upload check results
-        if: failure()
-        uses: actions/upload-artifact@main
+      - name: Upload coverage results
+        if: ${{ contains(matrix.config.flags, 'covr') && hashFiles('codecov.yml') != '' }}
+        uses: codecov/codecov-action@v4
         with:
-          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
-          path: check
+          fail_ci_if_error: ${{ github.event_name != 'pull_request' && true || false }}
+          file: ./cobertura.xml
+          plugin: noop
+          disable_search: true
+          token: ${{ secrets.CODECOV_TOKEN }}
